name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@master
        with: { python-version: 3.8 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: Install packages
        run: python -m pip install -r requirements.txt

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main_gui.py
          onefile: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/main_gui.exe
          include-hidden-files: true
